#!/bin/bash

#dependencies
sudo apt install patchelf '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev libyaml-cpp-dev 

script_path="$(cd "$(dirname $0)" && pwd)"

#qt installer
cd /tmp
wget https://d13lb3tujbc8s0.cloudfront.net/onlineinstallers/qt-unified-linux-x64-4.6.1-online.run
chmod +x ./qt*.run
./qt*.run

#arcgis installer
$script_path/arcgis/Setup

#launch script
git clone -b release https://github.com/Lab-RoCoCo-Sapienza/AGR-o-RAMA-GUI.git ~/.agrorama
cp ~/.agrorama/launch ~/Desktop/agrorama

# Make the desktop file executable
desktop_file="$script_path/Agrorama.desktop"
sudo chmod +x $desktop_file
sudo cp $desktop_file /usr/share/applications/
