#!/bin/bash

script_path="$(cd "$(dirname $0)" && pwd)"

$script_path/installers/qt-unified-linux-x64-4.6.1-online.run
$script_path/installers/arcgis/Setup

desktop_file="$script_path/Agrorama.desktop"

# Make the desktop file executable
sudo chmod +x $desktop_file
sudo cp $desktop_file /usr/share/applications/
